### PR TITLE
added: four func (+, -, /, *)

### PR DESCRIPTION
**Pull request by Bogdan-Natalochka**
all good?

### CODE REVIEW

**Comment by trotolena** [comment]
Bogdan's code looks good.

**Comment by trotolena** [comment]
@VladVidan what is your opinion?

**Comment by trotolena** [comment]
@Konstancia932 will you check it be flake8?

**Comment by VladVidan** [comment]
@Konstancia932 will check final version :) In my opinion @Bogdan-Natalochka code pretty good :)

**Comment by Konstancia932** [comment]
Yep, waiting for the final version

**Pull request merged**
